export const products = {
  kurti: [
    {
      id: 1,
      name: 'Earthen Bottle',
      href: '#',
      price: '₹100',
      color: 'Beige',
      discount: '30%',
      size: 'S',
      cross:'₹1,500',
      rating: '',
      imageSrc: 'https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/e/3/o/xl-sk-111-creationsakleni-original-imah93h4nyhsvsnm.jpeg?q=70',
      imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
    },
    {
      id: 2,
      name: 'Nomad Tumbler',
      href: '#',
      price: '₹600',
      color: 'Black',
      discount: '50%',
      size: 'M',
      cross:'₹1,200',
      rating: '',
      imageSrc: 'https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/m/d/q/s-t-jumping-0786-lakshya-fashion-mart-original-imah2tszaxahbfgw.jpeg?q=70',
      imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
    },
    {
      id: 3,
      name: 'Focus Paper Refill',
      href: '#',
      price: '₹500',
      color: 'Blue',
      discount: '60%',
      size: 'L',
      cross:'₹1,300',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/c3/9e/b7/c39eb7626442b2182b309b472fa28818.jpg',
      imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
    },
    {
      id: 4,
      name: 'Machined Mechanical Pencil',
      href: '#',
      price: '₹400',
      color: 'Yellow',
      discount: '80%',
      size: 'XL',
      cross:'₹2,990',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/f4/b9/b0/f4b9b0b37765816ba231317e1950265e.jpg',
      imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
    },
    {
      id: 5,
      name: 'Nomad Tumbler',
      href: '#',
      price: '₹800',
      color: 'White',
      discount: '70%',
      size: 'L',
      cross:'₹3,900',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/a7/1f/e4/a71fe458ca599bfa6e5aaca42f940d5c.jpg',
      imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
    },
    {
      id: 6,
      name: 'Focus Paper Refill',
      href: '#',
      price: '₹400',
      color: 'Dark Blue',
      discount: '40%',
      size: 'M',
      cross:'₹600',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/1f/bd/7d/1fbd7daa201370e934c6c55f684ddcc7.jpg',
      imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
    },
    {
      id: 7,
      name: 'Machined Mechanical Pencil',
      href: '#',
      price: '₹300',
      color: 'Orange',
      discount: '70%',
      size: 'L',
      cross:'₹1,800',
      rating: '',
      imageSrc: 'https://i.pinimg.com/736x/8d/83/57/8d8357d03b447cb28cc9beab6f487f8d.jpg',
      imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
    },
    {
      id: 8,
      name: 'Nomad Tumbler',
      href: '#',
      price: '₹200',
      color: 'Pink',
      discount: '40%',
      size: 'M',
      cross:'₹400',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/5c/2d/07/5c2d07ace3ec583be2bd2187055fd00a.jpg',
      imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
    },
    {
      id: 9,
      name: 'Focus Paper Refill',
      href: '#',
      price: '₹700',
      color: 'Green',
      discount: '50%',
      size: 'XL',
      cross:'₹1,400',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/60/32/aa/6032aa4a7e5cc7a708c23d0934f3d2d4.jpg',
      imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
    },
    {
      id: 10,
      name: 'Machined Mechanical Pencil',
      href: '#',
      price: '₹600',
      color: 'Dark Green',
      discount: '50%',
      size: '',
      cross:'₹1,200',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/7e/49/9a/7e499a8844c66f249eecd2cee8cbd505.jpg',
      imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
    },
    {
        id: 11,
        name: 'Earthen Bottle',
        href: '#',
        price: '₹100',
        color: 'Beige',
        discount: '30%',
        size: 'S',
        cross:'₹1,500',
        rating: '',
        imageSrc: 'https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/e/3/o/xl-sk-111-creationsakleni-original-imah93h4nyhsvsnm.jpeg?q=70',
        imageAlt: 'Tall slender porcelain bottle with natural clay textured body and cork stopper.',
      },
      {
        id: 12,
        name: 'Nomad Tumbler',
        href: '#',
        price: '₹600',
        color: 'Black',
        discount: '50%',
        size: '',
        cross:'₹1,200',
        rating: '',
        imageSrc: 'https://rukminim2.flixcart.com/image/612/612/xif0q/kurta/m/d/q/s-t-jumping-0786-lakshya-fashion-mart-original-imah2tszaxahbfgw.jpeg?q=70',
        imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
        id: 13,
        name: 'Focus Paper Refill',
        href: '#',
        price: '₹500',
        color: 'Blue',
        discount: '60%',
        size: '',
        cross:'₹1,300',
        rating: '',
        imageSrc: 'https://i.pinimg.com/474x/c3/9e/b7/c39eb7626442b2182b309b472fa28818.jpg',
        imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },
      {
        id: 14,
        name: 'Machined Mechanical Pencil',
        href: '#',
        price: '₹400',
        color: 'Yellow',
        discount: '80%',
        size: 'XL',
        cross:'₹2,990',
        rating: '',
        imageSrc: 'https://i.pinimg.com/474x/f4/b9/b0/f4b9b0b37765816ba231317e1950265e.jpg',
        imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
      },
      {
        id: 15,
        name: 'Nomad Tumbler',
        href: '#',
        price: '₹800',
        color: 'White',
        discount: '70%',
        size: 'L',
        cross:'₹3,900',
        rating: '',
        imageSrc: 'https://i.pinimg.com/474x/a7/1f/e4/a71fe458ca599bfa6e5aaca42f940d5c.jpg',
        imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
        id: 16,
        name: 'Focus Paper Refill',
        href: '#',
        price: '₹400',
        color: 'Dark Blue',
        discount: '40%',
        size: 'M',
        cross:'₹600',
        rating: '',
        imageSrc: 'https://i.pinimg.com/474x/1f/bd/7d/1fbd7daa201370e934c6c55f684ddcc7.jpg',
        imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },
      {
        id: 17,
        name: 'Machined Mechanical Pencil',
        href: '#',
        price: '₹300',
        color: 'Orange',
        discount: '70%',
        size: 'L',
        cross:'₹1,800',
        rating: '',
        imageSrc: 'https://i.pinimg.com/474x/04/68/97/046897c9b26440e1ef3478ac4ca956e1.jpg',
        imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
      },
      {
        id: 18,
        name: 'Nomad Tumbler',
        href: '#',
        price: '₹200',
        color: 'Pink',
        discount: '40%',
        size: 'M',
        cross:'₹400',
        rating: '',
        imageSrc: 'https://i.pinimg.com/474x/5c/2d/07/5c2d07ace3ec583be2bd2187055fd00a.jpg',
        imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
      },
      {
        id: 19,
        name: 'Focus Paper Refill',
        href: '#',
        price: '₹700',
        color: 'Green',
        discount: '50%',
        size: 'XL',
        cross:'₹1,400',
        rating: '',
        imageSrc: 'https://i.pinimg.com/474x/60/32/aa/6032aa4a7e5cc7a708c23d0934f3d2d4.jpg',
        imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
      },
      {
        id: 20,
        name: 'Machined Mechanical Pencil',
        href: '#',
        price: '₹600',
        color: 'Dark Green',
        discount: '50%',
        size: '',
        cross:'₹1,200',
        rating: '',
        imageSrc: 'https://i.pinimg.com/474x/7e/49/9a/7e499a8844c66f249eecd2cee8cbd505.jpg',
        imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
      },
  ],
  saree: [
    {
      id: 21,
      name: 'Machined Mechanical Pencil',
      href: '',
      price: '₹300',
      color: 'Orange',
      discount: '70%',
      size: 'L',
      cross:'₹1,800',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/cd/a4/f0/cda4f03ca3634bd2d155aa32520e8e4b.jpg',
      imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
    },
    {
      id: 22,
      name: 'Nomad Tumbler',
      href: '#',
      price: '₹200',
      color: 'Pink',
      discount: '40%',
      size: 'M',
      cross:'₹400',
      rating: '',
      imageSrc: 'https://rukminim2.flixcart.com/image/312/312/xif0q/sari/m/j/n/free-bollywood-cut-work-hot-pink-saree-bollytrend-unstitched-original-imah9cfbcdg4gy5h.jpeg?q=100',
      imageAlt: 'Olive drab green insulated bottle with flared screw lid and flat top.',
    },
    {
      id: 23,
      name: 'Focus Paper Refill',
      href: '#',
      price: '₹700',
      color: 'Green',
      discount: '50%',
      size: 'XL',
      cross:'₹1,400',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/4e/58/b7/4e58b719b464d87e461359fca9cfddc5.jpg',
      imageAlt: 'Person using a pen to cross a task off a productivity paper card.',
    },
    {
      id: 24,
      name: 'Machined Mechanical Pencil',
      href: '#',
      price: '₹600',
      color: 'Dark Green',
      discount: '50%',
      size: '',
      cross:'₹1,200',
      rating: '',
      imageSrc: 'https://i.pinimg.com/474x/30/cd/c0/30cdc09813cdffe2ad64c32b1ea86a93.jpg',
      imageAlt: 'Hand holding black machined steel mechanical pencil with brass tip and top.',
    },
  ],
};

products.all = [...products.kurti, ...products.saree];